3. Web MVC/UIWeb/Controllers/DataOutputController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Parser.DataBase;
using Parser.Handler;
using Parser.Model;
using System.Linq;

namespace UIWeb.Controllers
{
    public class DataOutputController : Controller
    {
        // GET: DataOutput
        public ActionResult Index()
        {
            List<Data_Repository> Receive = new List<Data_Repository>();
            DataHandler XML = new DataHandler();
            DBInteractive DB = new DBInteractive();
            
            Receive = XML.Parser(@"http://opendata.epa.gov.tw/ws/Data/UV/?format=xml");

            DB.DataBase_Clear();

            foreach (Data_Repository temp in Receive)
            {
                DB.DataBase_Write(temp);
            }

            ViewBag.Title = "顯示UV監控站資料";

            return View(Receive);
        }

        // GET: DataSearch
        public ActionResult DataSearch(string search = "")
        {
            List<Data_Repository> Receive = new List<Data_Repository>();
            DataHandler XML = new DataHandler();

            Receive = XML.Parser(@"http://opendata.epa.gov.tw/ws/Data/UV/?format=xml");

            if (!string.IsNullOrEmpty(search))
                Receive = Receive.Where(temp =>
                    temp._Parser_County.Contains(search) ||
                    temp._Parser_SiteName.Contains(search))
                    .ToList();

            ViewBag.Search = search;
            ViewBag.Title = "顯示UV監控站資料 - 搜尋結果";

            return View(Receive);
        }

        [HttpGet]
        public ActionResult DataDisplay(string id)
        {
            List<Data_Repository> Display = new List<Data_Repository>();
            DBInteractive DB = new DBInteractive();

            if (string.IsNullOrEmpty(id))
                Display = new List<Data_Repository>();
            else
                Display = DB.FindByID(id);

            ViewBag.Title = id + "站詳細資料";

            return View(Display);
        }
    }
}

3. Web MVC/UIWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UIWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(string id)
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

3. Web MVC/UIWeb/Views/DataOutput/DataDisplay.cshtml
@using Parser.Model;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Data_Repository> receive = Model;
}

<title>@ViewBag.Title - ASP.Net MVC Work</title>

<p></p>

@*詳細資料顯示*@
<div class="list-group">
    <a class="list-group-item active">
        紫外線監控站點  —  @receive[0]._Parser_SiteName 站詳細資料
    </a>

    @for (int i = 0; i < receive.Count; i++)
    {
        <a class="list-group-item">
            <h4 class="list-group-item-heading">站點名稱：@receive[i]._Parser_SiteName</h4>
            <p class="list-group-item-text">紫外線等級：@receive[i]._Parser_UVI</p>
            <p class="list-group-item-text">站點位置：@receive[i]._Parser_County</p>
            <p class="list-group-item-text">發布單位：@receive[i]._Parser_PublishAgency</p>
            <p class="list-group-item-text">站點位置：@receive[i]._Parser_County</p>
            <p class="list-group-item-text">站點經度：@receive[i]._Parser_WGS84Lon</p>
            <p class="list-group-item-text">站點緯度：@receive[i]._Parser_WGS84Lat</p>
        </a>
    }
</div>

3. Web MVC/UIWeb/Views/DataOutput/DataSearch.cshtml
@using Parser.Model;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Data_Repository> receive = Model;
}

<title>@ViewBag.Title - ASP.Net MVC Work</title>

<p></p>

@*Data Filter*@
<form class="form-inline" method="post" action="~/DataOutput/DataSearch">
    <div class="form-group">
        <input type="text" class="form-control" placeholder=@ViewBag.Search
               name="search" id="search"
               value="@ViewBag.Search">
    </div>

    <button type="submit" class="btn btn-default">搜尋</button>
    <button type="button" class="btn btn-default" onclick="javascript:window.location='@Url.Action("Index")'">返回</button>
</form>

<hr />

@*資料顯示*@
<div class="list-group">
    <a class="list-group-item active">
        紫外線監控站點  —  共有 @Model.Count 筆搜尋結果
    </a>

    @for (int i = 0; i < receive.Count; i++)
    {
        <a class="list-group-item"  href="/DataOutput/DataDisplay?id=@receive[i]._Parser_SiteName">
            <h4 class="list-group-item-heading">站點名稱：@receive[i]._Parser_SiteName</h4>
            <p class="list-group-item-text">站點位置：@receive[i]._Parser_County</p>
        </a>
    }
</div>

3. Web MVC/UIWeb/Views/DataOutput/Index.cshtml
@using Parser.Model;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Data_Repository> receive = Model;
}

<title>@ViewBag.Title - ASP.Net MVC Work</title>

<p></p>

@*Data Filter*@
<form class="form-inline" method="post" action="~/DataOutput/DataSearch">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="搜尋條件"
               name="search" id="search"
               value="@ViewBag.Search">
    </div>

    <button type="submit" class="btn btn-default">搜尋</button>
</form>

<hr />

@*資料顯示*@
<div class="list-group">
    <a class="list-group-item active">
        紫外線監控站點  —  共有 @Model.Count 筆資料
    </a>

    @for (int i = 0; i < receive.Count; i++)
    {
        <a class="list-group-item" href="/DataOutput/DataDisplay?id=@receive[i]._Parser_SiteName">
            <h4 class="list-group-item-heading">站點名稱：@receive[i]._Parser_SiteName</h4>
            <p class="list-group-item-text">站點位置：@receive[i]._Parser_County</p>
        </a>
    }
</div>

3. Web MVC/UIWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

3. Web MVC/UIWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

3. Web MVC/UIWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

3. Web MVC/UIWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.Net MVC Work</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ASP.Net MVC Work", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                    <li>@Html.ActionLink("顯示UV監控站資料", "Index", "DataOutput")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.Net MVC Work</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>